apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-exporter-ingress
  namespace: telegram-bots
spec:
  ingressClassName: nginx
  rules:
    - host: home-exporter.cash-track.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-exporter
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: home-exporter
  namespace: telegram-bots
spec:
  type: ClusterIP
  selector:
    app: home-exporter
  ports:
    - port: 80
      targetPort: 80
